--- 
- 
  become: true
  hosts: Appservers
  tasks: 
    - 
      name: "install java for tomcat"
      yum: 
        name: java
        state: present
    - 
      get_url: 
        dest: /opt
        url: "{{ tomcat_url }}"
      name: "download the tomcat from the official site"
    - 
      name: "untar the tomcat package"
      unarchive: 
        dest: /opt
        remote_src: true
        src: "/opt/{{ tomcat_package }}.tar.gz"
    - 
      command: "mv /opt/{{ tomcat_package }} /opt/tomcat/"
      name: "rename the tomcat directory"
    - 
      name: "start the tomcat service"
      shell: "nohup /opt/tomcat/bin/startup.sh"
  vars: 
    - 
      tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz"
    - 
      tomcat_package: apache-tomcat-8.5.78
